Stop periodically data polling thread
IOT-DSA/dslink-java-knx pull request #24
Opened 2016-10-06 18:26 UTC by hhou2011

@Pacane

2016-10-06 18:42 UTC, Pacane requested changes

2016-10-06 18:42 UTC, Pacane commented on src/main/java/org/dsa/iot/knx/KnxIPConnection.java
> +		if (pointToFutures.containsKey(address) || true == addressToPolled.get(address)) {
no need for the `== true`

2016-10-07 18:10 UTC, hhou2011 commented on src/main/java/org/dsa/iot/knx/KnxIPConnection.java
> +		if (pointToFutures.containsKey(address) || true == addressToPolled.get(address)) {
patched!

2016-10-07 18:14 UTC, Pacane approved these changes

2016-10-07 18:23 UTC, merged