Feature/feature remote device
IOT-DSA/dslink-java-knx pull request #43
Opened 2017-02-09 01:11 UTC by hhou2011

@Pacane @d-shapiro

2017-02-09 01:50 UTC, d-shapiro requested changes
restoreLastSession is still bugged - devices and points don't get restored. Their nodes are there, but without actions.

2017-02-09 20:27 UTC, Pacane requested changes
multiple missing implementations for getLabel?

2017-02-09 20:27 UTC, Pacane commented on src/main/java/org/dsa/iot/knx/KnxIPConnection.java
> +			String unit = null;
unit can be declared inline

2017-02-09 20:27 UTC, Pacane commented on src/main/java/org/dsa/iot/knx/KnxIPConnection.java
> +		unit = dpt.getUnit();
unit can be inline

2017-02-09 20:27 UTC, Pacane commented on src/main/java/org/dsa/iot/knx/datapoint/DPT1BitControlled.java
> +		// TODO Auto-generated method stub
missing implementation

2017-02-09 20:27 UTC, Pacane commented on src/main/java/org/dsa/iot/knx/datapoint/DPT2ByteFloat.java
> +		// TODO Auto-generated method stub
missing implementation

2017-02-09 20:27 UTC, Pacane commented on src/main/java/org/dsa/iot/knx/datapoint/DPT2ByteUnsigned.java
> +		// TODO Auto-generated method stub
missing implementation

2017-02-09 20:27 UTC, Pacane commented on src/main/java/org/dsa/iot/knx/datapoint/DPT3BitControlled.java
> +		// TODO Auto-generated method stub
missing implementation

2017-02-09 20:27 UTC, Pacane commented on src/main/java/org/dsa/iot/knx/datapoint/DPT4ByteFloat.java
> +		// TODO Auto-generated method stub
missing implementation

2017-02-09 21:04 UTC, hhou2011 commented on src/main/java/org/dsa/iot/knx/datapoint/DPT1BitControlled.java
> +		// TODO Auto-generated method stub
For controlled bit, no unit, but label.

2017-02-09 21:05 UTC, hhou2011 commented on src/main/java/org/dsa/iot/knx/datapoint/DPT2ByteFloat.java
> +		// TODO Auto-generated method stub
For the number type, just the unit, no label.

2017-02-09 21:12 UTC, d-shapiro approved these changes

2017-02-10 00:17 UTC, Pacane approved these changes

2017-02-10 00:41 UTC, merged